"""
main_agent.py — humanized, unified LangGraph voice agent for Sonic (restaurant
service robot). Replaces sonic_agent.py as the one script backend/launcher.py
spawns, for both trigger paths:

    - Dashboard "Take Order" click       -> TABLE_NO/SONIC_ACTION_HINT env vars
                                             set, table+intent already known.
    - Wake word ("Hi Sonic") + speech     -> continuous loop, intent AND table
                                             number (if mentioned) extracted
                                             from what the guest actually says.

Both paths converge on the same LangGraph StateGraph (build_graph() below).
sonic_agent.py is left untouched in the repo as a reference/legacy copy — this
file duplicates whatever infra it needs (DB, audio, STT/TTS, wake word, nav)
rather than importing it, since this is meant to be the only agent maintained
going forward.

Everything the robot says is generated by an LLM call at speak-time (render(),
see the "LLM layer" section) instead of a fixed f-string — this runs against
OpenAI (gpt-4o-mini by default, see LLM_URL/LLM_MODEL). A local Ollama model
on the Jetson was tried and rejected: the robot's own path planner
(ntfields_planner_node.py) already depends on the Jetson's GPU, and a local
LLM competing for that memory is a real risk to navigation, not worth
trading for chat latency — Groq/OpenAI-class cloud inference is already
fast, and cheap enough at this robot's conversation volume not to matter.
Swapping LLM_URL/LLM_MODEL is the only thing needed to point this at a
different provider/model; no node should ever need to change because of it.
Understanding what the guest said is a separate LLM call (extract_slots())
returning one consistent JSON envelope regardless of what's being asked, so a
single multi-item, multi-slot utterance ("4 spicy margherita pizzas and 2
fries") can supply everything in one turn — n_extract_items/route_active_item
below only ever asks for whatever slot is still actually missing.

Scope this round: take_order (and room_service, which maps to the same flow)
is the only intent fully built. Everything else a guest might say during the
wake-word greeting (menu, cutlery, call staff, about, bill, small talk,
delivery) routes to a single stub node (n_stub) that apologizes and hands off
to a human, rather than a full reimplementation — see n_stub. No mid-order
intent-switch-and-resume machinery either (sonic_agent.py had this) since
there's nowhere meaningful to switch to yet; an off-topic reply during any
ask-node just gets a brief redirect back to the same question.

Run modes (same three as sonic_agent.py, plus --test-mode):
    python main_agent.py               real mic/speaker/wake-word loop
    python main_agent.py --text-mode   typed input / printed output
    python main_agent.py --test-mode   real mic/speaker/wake-word loop, but
        every navigate_and_wait() call is an instant no-op arrival instead
        of a real Nav2 trip — everything else (wake word, listening, STT,
        LLM, TTS, ordering, menu browsing, confirm) is exercised for real.
        Combine with --text-mode too for a fully offline NLP-only test.
        Same effect as setting SONIC_SKIP_NAV=1.
    TABLE_NO=<n> SONIC_ACTION_HINT=<order|room_service|bill|deliver> set  ->
        one dispatched Kitchen->Table->Kitchen round trip, no wake word.

Requires OPENAI_API_KEY always (default model gpt-4o-mini — see
LLM_URL/LLM_MODEL to point elsewhere), SARVAM_API_KEY for real voice mode,
and DATABASE_URL (menu is DB-only, same as sonic_agent.py — run seed_db.py
first).
"""

from __future__ import annotations

import argparse
import base64
import difflib
import io
import json
import os
import queue
import re
import shlex
import subprocess
import sys
import threading
import time
import uuid as uuid_module
import wave
from dataclasses import asdict, dataclass, field
from datetime import datetime
from typing import Optional

import numpy as np
import psycopg2
import psycopg2.extras
import requests
import sounddevice as sd
from dotenv import load_dotenv
from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import END, StateGraph
from langgraph.types import Command, interrupt

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

load_dotenv()

SARVAM_API_KEY = os.environ.get("SARVAM_API_KEY")

# OpenAI (same OpenAI-compatible request/response shape Groq used, so
# LLMClient below needed no rewrite, just new defaults). A local Ollama
# model on the Jetson was tried and rejected: the robot's actual path
# planner (ntfields_planner_node.py, device='cuda') already depends on the
# Jetson's GPU/memory, and a local LLM competing for that is a real risk to
# navigation — not worth trading for chat latency. gpt-4o-mini over the
# nominally-cheaper gpt-5-nano: at this robot's conversation volume the
# price gap is pennies, and gpt-5-nano is a reasoning model with a
# different API shape (max_completion_tokens, no adjustable temperature,
# and unpredictable latency/cost unless reasoning_effort is pinned to
# "minimal") — not worth the integration risk for the savings.
LLM_URL = os.environ.get("LLM_URL", "https://api.openai.com/v1/chat/completions")
LLM_MODEL = os.environ.get("LLM_MODEL", "gpt-4o-mini")
LLM_API_KEY = os.environ.get("LLM_API_KEY") or os.environ.get("OPENAI_API_KEY")

SARVAM_STT_URL = "https://api.sarvam.ai/speech-to-text"
SARVAM_TTS_URL = "https://api.sarvam.ai/text-to-speech"
SARVAM_STT_MODEL = "saaras:v3"  # better code-mixed/noisy-speech accuracy than
# saarika:v2.5 (~19% vs ~22% WER on IndicVoices) and saarika is being
# deprecated by Sarvam.
SARVAM_TTS_MODEL = "bulbul:v3"
# English only, deliberately — Hindi/Hinglish auto-detection was tried and
# dropped: juggling per-turn language detection/switching (and Sarvam's STT
# occasionally misdetecting the language entirely) added real complexity for
# a narrow-scope restaurant deployment. en-IN, not en-US/generic "en" — this
# is Indian-accented English on both the STT and TTS side.
SARVAM_LANGUAGE_CODE = "en-IN"
SARVAM_SPEAKER = "ishita"   # a bulbul:v3 persona voice with a natural Indian-English accent
SARVAM_TTS_PACE = 1.0
SARVAM_TTS_WS_URL = "wss://api.sarvam.ai/text-to-speech/ws"
SARVAM_TTS_SAMPLE_RATE = 22050

WAKE_WORD_MODEL_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Hi_Sonic.onnx")
WAKE_WORD_NAME = "Hi_Sonic"
WAKE_WORD_THRESHOLD = 0.5

# The one ROS-aware subprocess this file shells out to — unmodified, shared
# with sonic_agent.py. Table coordinates stay JSON-file-only (office_map.json
# via nav_bridge.py) by deliberate choice; not migrated to Postgres.
NAV_BRIDGE_SCRIPT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "nav_bridge.py")
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NAV_TIMEOUT_S = 90.0

# Cross-process status feed for the dashboard — backend/launcher.py's
# /voice/status reads this the same way it already reads NAV_PROGRESS_PATH
# for the nav stack's own startup status. Written best-effort (see
# report_phase()); a failed write must never break the conversation.
VOICE_PROGRESS_PATH = "/tmp/argo_voice_progress"

SAMPLE_RATE = 16000
FRAME_MS = 30
FRAME_SAMPLES = SAMPLE_RATE * FRAME_MS // 1000

SILENCE_ONSET_TIMEOUT_S = 30.0  # how long a single listen attempt waits for speech to start
SILENCE_GIVEUP_TOTAL_S = 120.0  # cumulative silence (across reprompts) before giving up on a question
TRAILING_SILENCE_MS = 600
# int16 RMS energy a frame must exceed to count as "speech started" in
# record_utterance() — lower picks up quieter voices but also more room
# noise. Was dropped to 150 at one point for sensitivity, but that's below
# this robot's actual measured ambient noise floor (~280-500 RMS, live-
# probed with a bare sd.InputStream on real hardware) — record_utterance()
# uses this SAME threshold for both "has speech started" and "has speech
# ended" (RMS must drop below it for TRAILING_SILENCE_MS straight), so at
# 150 ambient noise alone never reads as silence and a listen attempt can
# hang indefinitely waiting for a quiet moment that never arrives. 550
# clears the highest ambient blip observed (~502) with margin, while still
# sitting comfortably below real speech peaks (900+ in the same probe) —
# override per-deployment via SONIC_RMS_THRESHOLD if your mic/room differs.
SPEECH_RMS_THRESHOLD = int(os.environ.get("SONIC_RMS_THRESHOLD", "550"))

TEXT_MODE = False

TRACE_ENABLED = os.environ.get("SONIC_TRACE", "1") != "0"


def trace(event: str, **fields) -> None:
    if not TRACE_ENABLED:
        return
    details = " ".join(f"{k}={v!r}" for k, v in fields.items())
    print(f"[trace] {event}" + (f" | {details}" if details else ""))


DATABASE_URL = os.environ.get("DATABASE_URL")
ROBOT_UID = os.environ.get("ROBOT_UID", "SONIC-001")
# Same wire contract backend/launcher.py already uses for sonic_agent.py —
# unchanged here so launcher.py only needs its script path repointed.
FORCED_LOCATION = os.environ.get("TABLE_NO") or None
FORCED_ACTION = os.environ.get("SONIC_ACTION_HINT") or None
MAP_NAME = os.environ.get("SONIC_MAP_NAME", "office_map")
# Test-only escape hatch: skip real Nav2 trips entirely and treat every
# navigate_and_wait() call as an instant arrival, so the rest of the
# conversation (wake word, listening, ordering, menu browsing, confirm,
# etc. — everything except actually driving) can be exercised end to end
# without a working ROS/Nav2 setup. Two ways to trigger it — the env var
# (unchanged, for scripts/CI) or `--test-mode` on the CLI (see main()),
# whichever's set wins. Never set this in production — a genuine nav
# failure should end the session (see n_navigate_to_table), not silently
# pretend the robot arrived somewhere it never went.
SONIC_SKIP_NAV = os.environ.get("SONIC_SKIP_NAV") == "1"

# order/room_service both run the full take_order flow (room_service has no
# dedicated flow yet, same as sonic_agent.py). bill/deliver are stubbed this
# round, same as any other not-yet-rewired intent — see n_stub.
DISPATCH_TAKE_ORDER_ACTIONS = {"order", "room_service"}


def require_api_keys(need_sarvam: bool = True) -> None:
    missing = []
    if not LLM_API_KEY:
        missing.append("OPENAI_API_KEY (get one from https://platform.openai.com)")
    if need_sarvam and not SARVAM_API_KEY:
        missing.append("SARVAM_API_KEY (get one from https://www.sarvam.ai)")
    if missing:
        print("Missing required API key(s):")
        for m in missing:
            print(f"  - {m}")
        print("Add them to a .env file (copy .env.example) before running.")
        sys.exit(1)
    # Fast-fail on a bad key/endpoint at startup, off the critical path,
    # rather than letting the very first real guest interaction discover it.
    try:
        t0 = time.monotonic()
        llm.chat("You are a helpful assistant.", "Reply with one word: ready", temperature=0.0, max_tokens=5)
        print(f"[main] LLM ({LLM_MODEL}) reachable, {time.monotonic() - t0:.1f}s round trip")
    except Exception as e:
        print(f"[warn] couldn't reach the LLM at {LLM_URL} ({e}) — check LLM_API_KEY/network. "
              "Spoken lines will fall back to a canned apology until this resolves.")


# ---------------------------------------------------------------------------
# Dialogue state
# ---------------------------------------------------------------------------

@dataclass
class OrderState:
    # trigger normalization — how this session started
    trigger_source: str = "voice"          # "ui" | "voice"
    table_no: Optional[str] = None
    location_reached: bool = False
    post_arrival_node: str = "n_greet_and_ask_order"   # where n_navigate_to_table goes once it arrives —
                                                        # data-driven so the menu intent can reuse the same
                                                        # nav step and land at n_menu_pick_category instead

    # conversation bookkeeping, fed to the LLM every turn
    conversation_history: list = field(default_factory=list)   # [{"role","text"}]
    pending_question: Optional[str] = None
    first_turn: bool = True

    # order building
    order_items: list = field(default_factory=list)     # committed line items this visit
    active_item: Optional[dict] = None                  # {item_id,name,category,quantity,preference,preference_asked}
    pending_items: list = field(default_factory=list)   # fully-seeded dicts queued from one multi-item utterance
    edit_target_name: Optional[str] = None

    # menu browsing (n_menu_pick_category / n_menu_answer_questions)
    active_menu_category: Optional[str] = None
    category_intro_said: bool = False   # has the category's item overview been spoken yet this visit —
                                         # own flag rather than reusing pending_question, which
                                         # get_reply_or_route() also writes on every ask

    # graph control flow
    next_node: Optional[str] = None
    went_idle: bool = False
    item_attempts: int = 0
    pending_seed: Optional[dict] = None    # a not-yet-consumed extraction outcome for the next node
    ask_retry: bool = False                # next ask_table/ask_qty should use its retry-flavored purpose,
                                            # not a second, unrelated fresh ask — see n_ask_table/n_ask_qty
    last_unmatched_item: Optional[str] = None   # n_extract_items' most recent no-menu-match name, for the retry prompt

    # Postgres handles (same schema sonic_agent.py used — no migration needed)
    db_session_id: Optional[str] = None
    db_visit_id: Optional[str] = None
    db_service_point_id: Optional[str] = None
    order_total: float = 0.0


TIMEOUT_SENTINEL = "__MAIN_AGENT_TIMEOUT__"

# speak_text() looks up "whose turn is this" via this module-level reference
# (kept current by trace_node()) rather than threading state through every
# call site — same pattern sonic_agent.py used.
_current_state: Optional[OrderState] = None


def table_ref_for_nav(table_no: str) -> str:
    """What nav_bridge.py should search for. It already matches a waypoint
    by its exact name field, case-insensitively — "Kitchen" finds whatever
    waypoint is named "Kitchen" regardless of its JSON key, "table 1" finds
    the waypoint actually named "table 1", no number-guessing involved.
    table_no is normally already the real waypoint name (the UI sends the
    clicked card's own name directly; a voice-triggered session's spoken
    table number goes through the SAME "Table {n}" convention every
    waypoint taught so far uses) — only a bare digit string needs wrapping,
    which happens for a guest's spoken "table 1" (NLU extracts just "1")."""
    return f"Table {table_no}" if table_no.isdigit() else table_no


def table_number_for_db(table_no: str) -> str:
    """Postgres service_points.label is seeded as "Table N" — a separate,
    numbered system from the nav waypoints above, unaffected by whatever a
    waypoint happens to be named. Pulls just the digits back out regardless
    of whether table_no is already a full name ("table 1"/"Table 3") or a
    bare number ("1") to begin with."""
    m = re.search(r"\d+", table_no)
    return m.group(0) if m else table_no


def order_summary(state: OrderState) -> str:
    if not state.order_items:
        return "no items yet"
    return ", ".join(
        f"{i['quantity']}x {i['name']}" + (f" ({i['preference']})" if i.get("preference") else "")
        for i in state.order_items
    )


def trace_node(name: str, state: OrderState) -> None:
    global _current_state
    _current_state = state
    trace(f"[graph] {name}", table=state.table_no, order=order_summary(state))


# ---------------------------------------------------------------------------
# Postgres persistence — optional (degrades to in-memory if DATABASE_URL
# isn't set), same schema/tables as sonic_agent.py, so the dashboard's
# existing order-reading code needs no changes.
# ---------------------------------------------------------------------------

DB_ROBOT_ID: Optional[str] = None
DB_LOCATION_ID: Optional[str] = None
_db_conn = None


def db():
    global _db_conn
    if not DATABASE_URL:
        return None
    if _db_conn is None or _db_conn.closed:
        try:
            _db_conn = psycopg2.connect(DATABASE_URL)
            _db_conn.autocommit = True
        except Exception as e:
            print(f"[warn] DB connection failed: {e}")
            _db_conn = None
    return _db_conn


def resolve_robot() -> None:
    global DB_ROBOT_ID, DB_LOCATION_ID
    conn = db()
    if conn is None:
        return
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT robot_id, location_id FROM robots WHERE robot_uid = %s", (ROBOT_UID,))
            row = cur.fetchone()
        if row is None:
            print(f"[warn] No robot row for ROBOT_UID={ROBOT_UID!r} — DB persistence disabled for this run.")
            return
        DB_ROBOT_ID, DB_LOCATION_ID = str(row[0]), str(row[1])
        print(f"[db] Connected — robot_id={DB_ROBOT_ID}, location_id={DB_LOCATION_ID}")
    except Exception as e:
        print(f"[warn] DB robot lookup failed: {e}")


def resolve_visit(state: OrderState) -> None:
    conn = db()
    if conn is None or DB_LOCATION_ID is None or state.db_visit_id or not state.table_no:
        return
    label = f"Table {table_number_for_db(state.table_no)}"
    try:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT service_point_id FROM service_points WHERE location_id = %s AND label = %s",
                (DB_LOCATION_ID, label),
            )
            row = cur.fetchone()
            if row is None:
                return
            service_point_id = row[0]

            cur.execute(
                """SELECT visit_id FROM visits WHERE service_point_id = %s AND visit_status = 'active'
                   ORDER BY checked_in_at DESC LIMIT 1""",
                (service_point_id,),
            )
            row = cur.fetchone()
            if row:
                visit_id = row[0]
            else:
                cur.execute(
                    "INSERT INTO visits (location_id, service_point_id) VALUES (%s, %s) RETURNING visit_id",
                    (DB_LOCATION_ID, service_point_id),
                )
                visit_id = cur.fetchone()[0]

            state.db_visit_id, state.db_service_point_id = str(visit_id), str(service_point_id)
            if state.db_session_id:
                cur.execute(
                    "UPDATE sonic_dialogue_sessions SET visit_id = %s, service_point_id = %s WHERE session_id = %s",
                    (state.db_visit_id, state.db_service_point_id, state.db_session_id),
                )
    except Exception as e:
        print(f"[warn] DB visit resolution failed: {e}")


def db_start_session(state: OrderState) -> None:
    conn = db()
    if conn is None or DB_ROBOT_ID is None or state.db_session_id:
        return
    resolve_visit(state)
    try:
        with conn.cursor() as cur:
            cur.execute(
                "INSERT INTO sonic_dialogue_sessions (robot_id, visit_id, service_point_id) VALUES (%s, %s, %s) RETURNING session_id",
                (DB_ROBOT_ID, state.db_visit_id, state.db_service_point_id),
            )
            state.db_session_id = str(cur.fetchone()[0])
    except Exception as e:
        print(f"[warn] DB session start failed: {e}")


def db_end_session(state: OrderState) -> None:
    conn = db()
    if conn is None or not state.db_session_id:
        return
    try:
        with conn.cursor() as cur:
            cur.execute("UPDATE sonic_dialogue_sessions SET ended_at = now() WHERE session_id = %s",
                        (state.db_session_id,))
    except Exception as e:
        print(f"[warn] DB session end failed: {e}")


def db_log_turn(state: OrderState, role: str, text: str, *,
                 intent: Optional[str] = None, slots: Optional[dict] = None) -> None:
    conn = db()
    if conn is None or not state.db_session_id:
        return
    try:
        with conn.cursor() as cur:
            cur.execute(
                """INSERT INTO sonic_dialogue_turns (session_id, role, text, detected_intent, slots)
                   VALUES (%s, %s, %s, %s, %s)""",
                (state.db_session_id, role, text, intent, psycopg2.extras.Json(slots) if slots else None),
            )
    except Exception as e:
        print(f"[warn] DB turn log failed: {e}")


def db_place_order(state: OrderState, items: list, total: float) -> None:
    conn = db()
    if conn is None or DB_LOCATION_ID is None:
        return
    resolve_visit(state)
    order_number = f"ORD-{datetime.now():%Y%m%d}-{uuid_module.uuid4().hex[:6].upper()}"
    try:
        with conn.cursor() as cur:
            cur.execute(
                """INSERT INTO orders (order_number, location_id, visit_id, service_point_id,
                                        order_source, order_status, subtotal_amount, total_amount, confirmed_at)
                   VALUES (%s, %s, %s, %s, 'voice_assistant', 'confirmed', %s, %s, now())
                   RETURNING order_id""",
                (order_number, DB_LOCATION_ID, state.db_visit_id, state.db_service_point_id, total, total),
            )
            order_id = cur.fetchone()[0]
            for item in items:
                unit_price = get_item_price(item)
                cur.execute(
                    """INSERT INTO order_items (order_id, menu_item_id, quantity, unit_price, line_total, special_request)
                       VALUES (%s, %s, %s, %s, %s, %s)""",
                    (order_id, item["item_id"], item["quantity"], unit_price,
                     unit_price * item["quantity"], item.get("preference")),
                )
    except Exception as e:
        print(f"[warn] DB order write failed: {e}")


def voice_nav_enabled() -> bool:
    conn = db()
    if conn is None or DB_LOCATION_ID is None:
        return True
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT voice_nav_enabled FROM locations WHERE location_id = %s", (DB_LOCATION_ID,))
            row = cur.fetchone()
            return bool(row[0]) if row else True
    except Exception as e:
        print(f"[warn] voice_nav_enabled check failed: {e}")
        return True


# ---------------------------------------------------------------------------
# Menu (Postgres-only, same as sonic_agent.py)
# ---------------------------------------------------------------------------

MENU_ITEMS: list = []
MENU_LOOKUP: dict = {}


def load_menu_from_db() -> None:
    global MENU_ITEMS, MENU_LOOKUP
    conn = db()
    if conn is None or DB_LOCATION_ID is None:
        print("No database/location available — menu can't be loaded. Set DATABASE_URL, "
              "then run run_migrations.py and seed_db.py.")
        sys.exit(1)
    try:
        with conn.cursor() as cur:
            cur.execute(
                """SELECT mi.menu_item_id, mi.item_name, mc.name, mi.price, mi.is_available, mi.description
                   FROM menu_items mi
                   LEFT JOIN menu_categories mc ON mi.category_id = mc.category_id
                   WHERE mi.location_id = %s""",
                (DB_LOCATION_ID,),
            )
            rows = cur.fetchall()
            cur.execute(
                """SELECT menu_item_id, alias FROM menu_item_aliases
                   WHERE menu_item_id IN (SELECT menu_item_id FROM menu_items WHERE location_id = %s)""",
                (DB_LOCATION_ID,),
            )
            alias_rows = cur.fetchall()
    except Exception as e:
        print(f"Menu load from DB failed: {e}")
        sys.exit(1)

    if not rows:
        print(f"No menu_items found for location_id={DB_LOCATION_ID} — run seed_db.py first.")
        sys.exit(1)

    aliases_by_item: dict = {}
    for menu_item_id, alias in alias_rows:
        aliases_by_item.setdefault(str(menu_item_id), []).append(alias)

    items = []
    for menu_item_id, item_name, category_name, price, is_available, description in rows:
        items.append({
            "item_id": str(menu_item_id),
            "name": item_name,
            "category": (category_name or "all").strip().lower(),
            "price": float(price),
            "available": is_available,
            "aliases": aliases_by_item.get(str(menu_item_id), []),
            "description": description or "",
        })

    lookup = {}
    for item in items:
        lookup[item["name"].strip().lower()] = item
        for alias in item["aliases"]:
            lookup[alias.strip().lower()] = item

    MENU_ITEMS, MENU_LOOKUP = items, lookup
    print(f"[db] Loaded {len(items)} menu items from Postgres")


def find_menu_item(spoken_name: Optional[str]) -> Optional[dict]:
    if not spoken_name:
        return None
    key = spoken_name.strip().lower()
    if key in MENU_LOOKUP:
        return MENU_LOOKUP[key]
    matches = difflib.get_close_matches(key, MENU_LOOKUP.keys(), n=1, cutoff=0.72)
    return MENU_LOOKUP[matches[0]] if matches else None


def menu_categories() -> list:
    return sorted({i["category"] for i in MENU_ITEMS if i["available"]})


def menu_items_by_category(category: str) -> list:
    return [i for i in MENU_ITEMS if i["available"] and i["category"] == category]


def menu_items_summary(items: list) -> str:
    """Pre-formatted for a render() context value — mirrors order_summary()'s
    convention (a plain readable string, not a raw list of dicts handed to
    .format())."""
    if not items:
        return "nothing available right now"
    return "; ".join(
        f"{i['name']} (${i['price']:.2f})" + (f" — {i['description']}" if i.get("description") else "")
        for i in items
    )


def find_menu_category(spoken_category: Optional[str]) -> Optional[str]:
    """Same fuzzy-match idea as find_menu_item(), but against the live
    category list rather than MENU_LOOKUP — categories aren't a fixed enum
    (see menu_categories()), so this is the only way to turn free text like
    "drinks" or "something spicy" into a real category value."""
    if not spoken_category:
        return None
    cats = menu_categories()
    key = spoken_category.strip().lower()
    for c in cats:
        if c == key:
            return c
    matches = difflib.get_close_matches(key, cats, n=1, cutoff=0.6)
    return matches[0] if matches else None


def get_item_price(order_item: dict) -> float:
    for m in MENU_ITEMS:
        if m["item_id"] == order_item["item_id"]:
            return m["price"]
    return 0.0


def find_order_line(state: OrderState, name: Optional[str]) -> Optional[dict]:
    if not name:
        return None
    match = find_menu_item(name)
    target_name = match["name"] if match else name
    for line in state.order_items:
        if line["name"].lower() == target_name.lower():
            return line
    for line in state.order_items:
        if target_name.lower() in line["name"].lower() or line["name"].lower() in target_name.lower():
            return line
    return None


# ---------------------------------------------------------------------------
# Audio I/O
# ---------------------------------------------------------------------------

def record_utterance(timeout_s: float = SILENCE_ONSET_TIMEOUT_S) -> Optional[np.ndarray]:
    q: queue.Queue = queue.Queue()

    def callback(indata, frames, time_info, status):
        q.put(indata.copy())

    frames_collected = []
    speech_started = False
    silence_run_ms = 0
    start = time.monotonic()

    with sd.InputStream(samplerate=SAMPLE_RATE, channels=1, dtype="int16",
                         blocksize=FRAME_SAMPLES, callback=callback):
        while True:
            try:
                chunk = q.get(timeout=0.5)
            except queue.Empty:
                if not speech_started and (time.monotonic() - start) > timeout_s:
                    return None
                continue

            rms = float(np.sqrt(np.mean(chunk.astype(np.float64) ** 2)))

            if not speech_started:
                if rms > SPEECH_RMS_THRESHOLD:
                    speech_started = True
                    frames_collected.append(chunk)
                elif (time.monotonic() - start) > timeout_s:
                    return None
                continue

            frames_collected.append(chunk)
            if rms > SPEECH_RMS_THRESHOLD:
                silence_run_ms = 0
            else:
                silence_run_ms += FRAME_MS
                if silence_run_ms >= TRAILING_SILENCE_MS:
                    break

    return np.concatenate(frames_collected, axis=0).flatten()


def play_audio(audio: np.ndarray, samplerate: int = SAMPLE_RATE) -> None:
    sd.play(audio, samplerate=samplerate)
    sd.wait()


# ---------------------------------------------------------------------------
# Sarvam AI: STT (saaras:v3) / TTS (bulbul:v3)
# ---------------------------------------------------------------------------

def sarvam_stt(audio: np.ndarray) -> str:
    """English-only, deliberately (see SARVAM_LANGUAGE_CODE) — pinning the
    language_code instead of using "unknown" auto-detect also sidesteps the
    misdetection problem auto-detect had (confidently transcribing into an
    unrelated language on ambiguous/quiet audio)."""
    buf = io.BytesIO()
    with wave.open(buf, "wb") as wf:
        wf.setnchannels(1)
        wf.setsampwidth(2)
        wf.setframerate(SAMPLE_RATE)
        wf.writeframes(audio.astype(np.int16).tobytes())
    buf.seek(0)

    resp = requests.post(
        SARVAM_STT_URL,
        headers={"api-subscription-key": SARVAM_API_KEY},
        data={"model": SARVAM_STT_MODEL, "language_code": SARVAM_LANGUAGE_CODE},
        files={"file": ("utterance.wav", buf, "audio/wav")},
        timeout=30,
    )
    resp.raise_for_status()
    data = resp.json()
    return (data.get("transcript") or data.get("text") or "").strip()


def sarvam_tts(text: str, language_code: str = SARVAM_LANGUAGE_CODE) -> tuple[np.ndarray, int]:
    resp = requests.post(
        SARVAM_TTS_URL,
        headers={"api-subscription-key": SARVAM_API_KEY, "Content-Type": "application/json"},
        json={
            "inputs": [text],
            "target_language_code": language_code,
            "model": SARVAM_TTS_MODEL,
            "speaker": SARVAM_SPEAKER,
            "pace": SARVAM_TTS_PACE,
        },
        timeout=30,
    )
    resp.raise_for_status()
    data = resp.json()
    audios = data.get("audios") or []
    if not audios:
        raise RuntimeError(f"Sarvam TTS returned no audio: {data}")
    raw = base64.b64decode(audios[0])
    with wave.open(io.BytesIO(raw), "rb") as wf:
        sr = wf.getframerate()
        pcm = np.frombuffer(wf.readframes(wf.getnframes()), dtype=np.int16)
    return pcm, sr


def sarvam_tts_stream(sentences: list, language_code: str = SARVAM_LANGUAGE_CODE) -> bool:
    try:
        import websockets.sync.client as ws_client
    except ImportError:
        return False

    played_any = False
    stream = None
    url = f"{SARVAM_TTS_WS_URL}?model={SARVAM_TTS_MODEL}&send_completion_event=true"
    try:
        with ws_client.connect(url, additional_headers={"Api-Subscription-Key": SARVAM_API_KEY}) as ws:
            ws.send(json.dumps({
                "type": "config",
                "data": {
                    "language_code": language_code,
                    "speaker": SARVAM_SPEAKER,
                    "model": SARVAM_TTS_MODEL,
                    "pace": SARVAM_TTS_PACE,
                    "speech_sample_rate": SARVAM_TTS_SAMPLE_RATE,
                    "output_audio_codec": "linear16",
                },
            }))
            for sentence in sentences:
                ws.send(json.dumps({"type": "text", "data": {"text": sentence}}))
                ws.send(json.dumps({"type": "flush"}))

            stream = sd.OutputStream(samplerate=SARVAM_TTS_SAMPLE_RATE, channels=1, dtype="int16")
            stream.start()

            pending = len(sentences)
            while pending > 0:
                msg = json.loads(ws.recv(timeout=20))
                mtype = msg.get("type")
                if mtype == "audio":
                    pcm = np.frombuffer(base64.b64decode(msg["data"]["audio"]), dtype=np.int16)
                    if pcm.size:
                        stream.write(pcm)
                        played_any = True
                elif mtype == "event" and msg.get("data", {}).get("event_type") == "final":
                    pending -= 1
                elif mtype == "error":
                    print(f"[warn] Sarvam streaming TTS error: {msg}")
                    return played_any
        return True
    except Exception as e:
        print(f"[warn] Sarvam streaming TTS {'ended early' if played_any else 'unavailable, falling back to REST'}: {e}")
        return played_any
    finally:
        if stream is not None:
            stream.stop()
            stream.close()


_SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?])\s+")


def split_sentences(text: str) -> list:
    parts = _SENTENCE_SPLIT_RE.split(text.strip())
    return [p for p in parts if p]


def _chunk_into_sentences(text_stream):
    """Buffers streamed text deltas (e.g. from LLMClient.chat_stream()) and
    yields each complete sentence as soon as its terminal punctuation AND
    the text after it have arrived — same boundary rule split_sentences()
    uses (_SENTENCE_SPLIT_RE), just applied incrementally so TTS can start
    on sentence 1 while the LLM is still generating sentence 2+, instead of
    waiting for the whole response first."""
    buf = ""
    for delta in text_stream:
        buf += delta
        parts = _SENTENCE_SPLIT_RE.split(buf)
        for complete in parts[:-1]:
            complete = complete.strip()
            if complete:
                yield complete
        buf = parts[-1]
    buf = buf.strip()
    if buf:
        yield buf


def speak_text(text: str) -> None:
    """Low-level: prints, logs the turn, and does TTS playback for an
    already-complete string. Used by the interrupt-prompt path in
    run_graph_session() (listen_with_patience()) — that path needs the full
    rendered text before it can even call interrupt(), so streaming doesn't
    help there (see speak_stream() below, used by say() instead, for
    fire-and-forget lines where it does)."""
    print(f"Sonic: {text}")
    if _current_state is not None:
        _current_state.conversation_history.append({"role": "robot", "text": text})
        db_log_turn(_current_state, "robot", text)
    if TEXT_MODE:
        return

    sentences = split_sentences(text)
    if not sentences:
        return

    if sarvam_tts_stream(sentences):
        return

    audio_queue: "queue.Queue" = queue.Queue(maxsize=2)
    DONE = object()

    def synthesize_worker():
        for sentence in sentences:
            try:
                audio_queue.put(sarvam_tts(sentence))
            except Exception as e:
                print(f"[warn] TTS failed for a chunk: {e}")
        audio_queue.put(DONE)

    worker = threading.Thread(target=synthesize_worker, daemon=True)
    worker.start()

    while True:
        item = audio_queue.get()
        if item is DONE:
            break
        audio, sr = item
        try:
            play_audio(audio, sr)
        except Exception as e:
            print(f"[warn] audio playback failed: {e}")
    worker.join(timeout=1.0)


def speak_stream(sentence_iter) -> None:
    """Streaming sibling of speak_text() — plays each sentence via TTS as
    soon as render_stream() has it, instead of waiting for the whole
    response to finish generating before starting TTS on any of it. Same
    background-thread-synthesizes/main-thread-plays queue shape speak_text()
    already uses for its own REST fallback, just fed by the streaming
    sentence generator instead of a pre-split list — synthesis of sentence
    N+1 can overlap with sentence N still playing. Uses plain sarvam_tts()
    per sentence rather than sarvam_tts_stream() — a single short sentence
    doesn't benefit from a websocket over one REST call, and this avoids
    reopening a websocket per sentence. Logs the full accumulated text as
    ONE conversation_history/db_log_turn entry once the stream ends, same
    one-entry-per-turn convention speak_text() uses (not one per sentence)."""
    spoken_parts = []
    audio_queue: "queue.Queue" = queue.Queue(maxsize=2)
    DONE = object()

    def synthesize_worker():
        for sentence in sentence_iter:
            spoken_parts.append(sentence)
            print(f"Sonic: {sentence}")
            if TEXT_MODE:
                continue
            try:
                audio_queue.put(sarvam_tts(sentence))
            except Exception as e:
                print(f"[warn] TTS failed for a chunk: {e}")
        audio_queue.put(DONE)

    worker = threading.Thread(target=synthesize_worker, daemon=True)
    worker.start()

    if not TEXT_MODE:
        while True:
            item = audio_queue.get()
            if item is DONE:
                break
            audio, sr = item
            try:
                play_audio(audio, sr)
            except Exception as e:
                print(f"[warn] audio playback failed: {e}")
    worker.join(timeout=1.0)

    full_text = " ".join(spoken_parts)
    if _current_state is not None:
        _current_state.conversation_history.append({"role": "robot", "text": full_text})
        db_log_turn(_current_state, "robot", full_text)


def listen(timeout_s: float = SILENCE_ONSET_TIMEOUT_S) -> Optional[str]:
    """Returns the transcript — which may be "" — or None specifically when
    no speech was ever detected within timeout_s (record_utterance's RMS
    gate never triggered: genuine silence). "" means something DID trigger
    the mic (noise, a false RMS blip, a garbled attempt, an STT error) but
    produced no usable text — callers must treat that differently from real
    silence, see listen_with_patience()."""
    if TEXT_MODE:
        try:
            text = input("You: ").strip()
        except EOFError:
            print()
            sys.exit(0)
        if text.lower() in ("quit", "exit"):
            print("Goodbye!")
            sys.exit(0)
        return text or None

    audio = record_utterance(timeout_s)
    if audio is None:
        return None
    try:
        transcript = sarvam_stt(audio)
    except Exception as e:
        print(f"[warn] STT failed: {e}")
        transcript = ""
    print(f"You said: {transcript}")
    return transcript


def listen_with_patience(prompt_text: str) -> Optional[str]:
    """Speak the prompt, then wait through silence rather than bailing
    quickly. Tracks real elapsed wall-clock time (not an assumed fixed
    increment per attempt), and treats two kinds of "no reply" differently:
      - genuine silence (RMS gate never triggered for a full listen window)
        — worth repeating the question, in case they missed it or stepped
        away.
      - something was heard but didn't transcribe to anything usable (a
        stray noise, a false trigger) — NOT treated as silence, and does
        NOT repeat the question; just listens again immediately, since
        talking over someone who's mid-answer is worse than trying again
        quietly.
    Gives up only once SILENCE_GIVEUP_TOTAL_S of total real elapsed time has
    passed with no actual reply. An actual reply at any point returns
    immediately, however long the exchange has been going."""
    speak_text(prompt_text)
    start = time.monotonic()
    while True:
        remaining = SILENCE_GIVEUP_TOTAL_S - (time.monotonic() - start)
        if remaining <= 0:
            return None
        reply = listen(timeout_s=min(SILENCE_ONSET_TIMEOUT_S, remaining))
        if reply:
            return reply
        if reply is None and (time.monotonic() - start) < SILENCE_GIVEUP_TOTAL_S:
            speak_text(prompt_text)


# ---------------------------------------------------------------------------
# Wake word (openWakeWord + Hi_Sonic.onnx)
# ---------------------------------------------------------------------------

def load_wake_word_model():
    try:
        from openwakeword import Model
    except ImportError:
        from openwakeword.model import Model
    return Model(wakeword_models=[WAKE_WORD_MODEL_PATH], inference_framework="onnx")


def wait_for_wake_word(oww_model) -> None:
    oww_model.reset()
    q: queue.Queue = queue.Queue()

    def callback(indata, frames, time_info, status):
        q.put(indata.copy().flatten())

    with sd.InputStream(samplerate=SAMPLE_RATE, channels=1, dtype="int16",
                         blocksize=1280, callback=callback):
        while True:
            chunk = q.get()
            predictions = oww_model.predict(chunk)
            score = predictions.get(WAKE_WORD_NAME)
            if score is None and predictions:
                score = next(iter(predictions.values()))
            if score is not None and score > WAKE_WORD_THRESHOLD:
                return


# ---------------------------------------------------------------------------
# Navigation — shells out to the existing, unmodified sonic/nav_bridge.py
# ---------------------------------------------------------------------------

def report_phase(phase: Optional[str], text: str = "", table: Optional[str] = None) -> None:
    """Writes the current macro-phase (heading_to_table/arrived/taking_order/
    heading_to_kitchen, or None to clear) to VOICE_PROGRESS_PATH so
    backend/launcher.py's /voice/status can surface real status to the
    dashboard instead of the frontend simulating it. Best-effort — this is
    display plumbing, never allowed to affect the conversation itself."""
    try:
        with open(VOICE_PROGRESS_PATH, "w") as f:
            json.dump({"phase": phase, "text": text, "table": table,
                       "updated_at": datetime.now().isoformat()}, f)
    except OSError as e:
        print(f"[warn] report_phase write failed: {e}")


def navigate_and_wait(destination: str, timeout_s: float = NAV_TIMEOUT_S) -> bool:
    if SONIC_SKIP_NAV:
        print(f"[nav] test mode — treating {destination!r} as instantly reached, not actually driving")
        return True
    if not voice_nav_enabled():
        print(f"[nav] voice_nav_enabled is off — skipping trip to {destination!r}")
        return False

    cmd = (
        "source /opt/ros/humble/setup.bash && "
        f"source {REPO_ROOT}/install/setup.bash && "
        "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp && "
        f"python3 {shlex.quote(NAV_BRIDGE_SCRIPT)} --map {shlex.quote(MAP_NAME)} "
        f"--destination {shlex.quote(destination)} --timeout {timeout_s}"
    )
    print(f"[nav] -> {destination!r} (timeout {timeout_s:.0f}s)")
    try:
        result = subprocess.run(["bash", "-c", cmd], capture_output=True, text=True, timeout=timeout_s + 15)
    except subprocess.TimeoutExpired:
        print(f"[nav] {destination!r}: bridge process itself timed out")
        return False

    ok = result.returncode == 0 and "RESULT:SUCCESS" in result.stdout
    print(f"[nav] {destination!r}: {'arrived' if ok else 'FAILED'} (rc={result.returncode})")
    if not ok:
        # nav_bridge.py logs its own diagnosis (action server not found,
        # goal rejected, timeout reason, ...) via plain print() — stdout,
        # not stderr — so stderr alone was silently swallowing the actual
        # reason for every failure, leaving only an uninformative rc=1.
        if result.stdout:
            print(f"[nav] stdout: {result.stdout.strip()[-1000:]}")
        if result.stderr:
            print(f"[nav] stderr: {result.stderr.strip()[-500:]}")
    return ok


def perform_travel_action(state: OrderState, announce_purpose: str, destination: str, **ctx) -> bool:
    # Fire the nav goal immediately, in parallel with the spoken
    # announcement — say() (an LLM call to render the line, TTS synthesis,
    # then blocking playback of the full sentence) used to run to
    # completion BEFORE navigate_and_wait() even started the nav_bridge
    # subprocess, so the robot sat still through the whole announcement.
    # That read as "waits 10 seconds before moving": the wheels were
    # waiting on speech, not on Nav2.
    result: list[bool] = []
    nav_thread = threading.Thread(target=lambda: result.append(navigate_and_wait(destination)))
    nav_thread.start()
    say(announce_purpose, state, **ctx)
    nav_thread.join()
    return result[0] if result else False


# ---------------------------------------------------------------------------
# LLM layer — the "no hardcoded talk" seam. Two call shapes:
#   extract_slots() — understand what the guest said, one consistent schema.
#   render()        — decide what to say next, one call per outgoing line.
# Both go through LLMClient.chat(); swapping to a local model later means
# changing LLMClient's construction, not any node.
# ---------------------------------------------------------------------------

class GroqJSONError(RuntimeError):
    def __init__(self, message: str, failed_generation: Optional[str] = None):
        super().__init__(message)
        self.failed_generation = failed_generation


class LLMClient:
    def __init__(self, base_url: str = LLM_URL, model: str = LLM_MODEL, api_key: Optional[str] = None):
        self.base_url = base_url
        self.model = model
        self.api_key = api_key or LLM_API_KEY

    def chat(self, system: str, user: str, *, json_mode: bool = False, temperature: float = 0.2,
              max_tokens: Optional[int] = None, messages_override: Optional[list] = None) -> str:
        messages = messages_override or [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ]
        payload = {"model": self.model, "messages": messages, "temperature": temperature}
        if max_tokens:
            payload["max_tokens"] = max_tokens
        if json_mode:
            payload["response_format"] = {"type": "json_object"}

        last_err = None
        for attempt in range(2):
            payload["temperature"] = temperature + (0.15 if attempt > 0 else 0.0)
            try:
                resp = requests.post(
                    self.base_url,
                    headers={"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"},
                    json=payload,
                    timeout=30,
                )
                if not resp.ok:
                    body_text = resp.text[:2000]
                    failed_generation = None
                    try:
                        failed_generation = resp.json().get("error", {}).get("failed_generation")
                    except Exception:
                        pass
                    if failed_generation:
                        raise GroqJSONError(f"{resp.status_code} {resp.reason}: {body_text[:500]}",
                                             failed_generation=failed_generation)
                    raise RuntimeError(f"{resp.status_code} {resp.reason}: {body_text[:500]}")
                return resp.json()["choices"][0]["message"]["content"]
            except Exception as e:
                last_err = e
                time.sleep(0.5)
        if isinstance(last_err, GroqJSONError):
            raise last_err
        raise RuntimeError(f"LLM call failed after retries: {last_err}")

    def chat_stream(self, system: str, user: str, *, temperature: float = 0.6,
                     max_tokens: Optional[int] = None):
        """Yields text deltas as the LLM streams its completion (SSE), instead
        of blocking for the whole response like chat() does — used only for
        spoken-line generation (render_stream()), never for extraction
        (extract_slots() needs the complete JSON object before it can parse
        anything, so it stays on the blocking chat() above). No retry-on-
        error here unlike chat() — a mid-stream failure is caught by the
        caller (render_stream()) and falls back to chat() entirely, same
        shape as sarvam_tts_stream() falling back to sarvam_tts()."""
        messages = [{"role": "system", "content": system}, {"role": "user", "content": user}]
        payload = {"model": self.model, "messages": messages, "temperature": temperature, "stream": True}
        if max_tokens:
            payload["max_tokens"] = max_tokens
        resp = requests.post(
            self.base_url,
            headers={"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"},
            json=payload,
            stream=True,
            timeout=30,
        )
        resp.raise_for_status()
        for line in resp.iter_lines():
            if not line or not line.startswith(b"data: "):
                continue
            chunk = line[len(b"data: "):]
            if chunk == b"[DONE]":
                return
            delta = json.loads(chunk)["choices"][0]["delta"].get("content")
            if delta:
                yield delta


llm = LLMClient()

_WRAPPING_QUOTES = '"\'“”‘’'


def clean_spoken_text(text: Optional[str]) -> str:
    if not text:
        return ""
    cleaned = text.strip().strip(_WRAPPING_QUOTES).strip()
    if cleaned and cleaned[0].isalpha():
        cleaned = cleaned[0].upper() + cleaned[1:]
    return cleaned


WAITER_PERSONA = (
    "You are Sonic, a warm and genuinely friendly restaurant service robot taking a table's food order "
    "in person. Sound like an attentive human waiter, not a script — vary your phrasing naturally rather "
    "than repeating the same sentence structure every time. Speak natural Indian English — the guest is "
    "in India, so phrase things the way an Indian waiter would, not American/British English. Keep replies "
    "to 1-2 short spoken sentences. Never wrap your reply in quotation marks — plain spoken text only. "
    "Never invent menu items, prices, or facts that aren't given to you in the context below."
)

RENDER_PURPOSE_HINTS = {
    "ask_how_can_i_help": "They just said your wake word and you're now listening — give ONLY a very short acknowledgment that you heard them and are ready, 1-4 words, e.g. \"Hi!\", \"Hello!\", \"Yes?\", \"I'm here!\", \"I'm awake!\". NOT a full sentence, and don't ask what they'd like — they'll just say it. This opens with zero conversation history every time, so vary which short phrase you use rather than repeating the same one every time.",
    "ask_table": "Ask which table you should come to.",
    "ask_table_retry": "You didn't catch a valid table number. Ask again, briefly.",
    "heading_to_table": "Let them know you're heading to {table_ref} now and will be right there.",
    "arrived_greet_and_ask_order": "You've just arrived at the table. Greet them warmly and ask what they'd like to order. This opens with zero conversation history every time, so nothing about the prompt itself varies call to call — deliberately vary your wording, phrasing, and structure so it sounds like a real person greeting a table, not the same scripted line on repeat.",
    "ask_what_would_you_like": "Ask what they'd like to order.",
    "item_not_found": "You couldn't find \"{item_name}\" on the menu. Apologize briefly and ask them to say the dish name again.",
    "reprompt_unclear_item": "You still couldn't understand which dish they want after a few tries. Apologize and let them know you'll come back to it in a moment.",
    "ask_quantity": "Ask how many {item_name} they'd like.",
    "ask_quantity_retry": "That wasn't a usable number. Ask again how many {item_name} they'd like, briefly.",
    "ask_preference": "Ask if they'd like any customization or preference for {item_name} — e.g. spice level, no onions.",
    "ask_anything_else": "Ask if they'd like to add anything else to their order.",
    "yes_no_unclear": "You couldn't tell if that was a yes or a no. Ask them to clarify, briefly.",
    "confirm_readback": "Read back their full order naturally — {order_summary} — and ask if you should confirm it as-is.",
    "confirm_reject_choice": "They didn't want to confirm the order as it stands. Ask if they'd like to cancel it entirely, or change something in it.",
    "cancel_or_change_unclear": "You couldn't tell if they want to cancel or change something. Ask them to clarify, briefly.",
    "cancel_confirmed": "Let them know their order has been cancelled.",
    "nothing_to_edit": "Let them know there's nothing in their order yet to change.",
    "edit_ask_target": "Read back their order — {order_summary} — and ask which item they'd like to change, and how.",
    "edit_target_not_found": "You couldn't find \"{item_name}\" in their order. Apologize and ask again which item they mean.",
    "edit_applied": "Let them know the change was made: {change_summary}.",
    "nothing_new_to_confirm": "Gently let them know there's nothing new in their order to confirm right now.",
    "closing_thanks": "Their order — {order_summary} — is confirmed and headed to the kitchen. Thank them warmly.",
    "apology_nav_failed": "Apologize that you're having trouble getting to the table right now and ask for someone's help.",
    "redirect_off_topic": "They just said something unrelated to what you asked (\"{last_said}\"). Respond to it briefly and warmly — you'll repeat your actual question right after this.",
    "stub_unavailable": "They asked about {requested_intent}, which you can't help with by voice yet. Apologize briefly and let them know a staff member will help with that.",
    "idle_timeout_farewell": "They didn't respond. Give a brief, warm goodbye / see-you-later line.",
    "menu_ask_category": "Ask which part of the menu they'd like to hear about — options are: {categories}. Mention a few naturally, like a waiter chatting through what's on offer, not a robotic recitation of the full list.",
    "menu_ask_category_retry": "You didn't catch a menu category from that. Ask again, briefly, mentioning a couple of options — options are: {categories}.",
    "menu_describe_category": "Tell them warmly what's available in {category} — {items} — like a waiter describing the menu, not reading out a price list. Then ask if anything sounds good, or if they'd like to hear about something else.",
    "menu_answer_question": "They asked: \"{question}\". Answer it naturally using what you know about {category} — {items}. Then let them know they can order, hear about another category, or you're happy to keep chatting.",
    "menu_browse_farewell": "They're done browsing the menu for now and aren't ordering yet. Give a brief, warm sign-off — let them know you're happy to come back whenever they're ready.",
    "delivery_arrived": "You've just arrived at the table carrying their order. Let them know it's here, and ask them to let you know once they've picked it up so you can head back.",
    "delivery_confirm_retry": "You're still waiting for them to pick up their order off you. Ask again, briefly and patiently, whether they've got it yet.",
    "delivery_confirmed": "They've picked up their order. Give a brief, warm sign-off — enjoy the meal — before you head back to the kitchen.",
}


def _build_render_prompt(purpose: str, state: OrderState, **ctx) -> str:
    hint = RENDER_PURPOSE_HINTS.get(purpose, purpose)
    try:
        hint = hint.format(**ctx)
    except (KeyError, IndexError):
        pass
    history_tail = state.conversation_history[-6:]
    history_text = "\n".join(f"{t['role']}: {t['text']}" for t in history_tail) or "(nothing yet)"
    return (
        f"Recent conversation:\n{history_text}\n\n"
        f"What to say now: {hint}"
    )


RENDER_MAX_TOKENS = 200  # a couple of spoken sentences' worth — backstop against a small model rambling


def render(purpose: str, state: OrderState, **ctx) -> str:
    user_prompt = _build_render_prompt(purpose, state, **ctx)
    try:
        text = llm.chat(WAITER_PERSONA, user_prompt, temperature=0.6, max_tokens=RENDER_MAX_TOKENS)
    except Exception as e:
        print(f"[warn] render failed for purpose={purpose!r}: {e}")
        return "Sorry, I'm having a little trouble right now — one moment."
    return clean_spoken_text(text) or "Sorry, one moment."


def render_stream(purpose: str, state: OrderState, **ctx):
    """Streaming sibling of render() — yields complete sentences as the LLM
    generates them, instead of blocking for the whole response first. Falls
    back to a single yield of render()'s full (blocking) result on any
    failure, so callers never see a broken stream — same fall-back-to-
    blocking shape sarvam_tts_stream() already uses in this file."""
    user_prompt = _build_render_prompt(purpose, state, **ctx)
    try:
        any_yielded = False
        for sentence in _chunk_into_sentences(
                llm.chat_stream(WAITER_PERSONA, user_prompt, temperature=0.6, max_tokens=RENDER_MAX_TOKENS)):
            cleaned = clean_spoken_text(sentence)
            if cleaned:
                any_yielded = True
                yield cleaned
        if not any_yielded:
            yield "Sorry, one moment."
    except Exception as e:
        print(f"[warn] render_stream failed for purpose={purpose!r}, falling back to render(): {e}")
        yield render(purpose, state, **ctx)


def say(purpose: str, state: OrderState, **ctx) -> None:
    speak_stream(render_stream(purpose, state, **ctx))


EXTRACTION_SCHEMA = """{
  "intent": "<take_order, menu, cutlery, call_people, about, get_bill, navigation, normal_conv, or null>",
  "table_no": "<the table number mentioned, as a string, or null>",
  "answers_pending": <true/false — does this utterance actually address what was just asked?>,
  "items": [{"item_name": "<dish name>", "quantity": <integer or null>, "preference": "<free text or null>"}],
  "quantity": <integer or null>,
  "preference": "<free text or null>",
  "yes_no": "<yes, no, or null>",
  "wants_more": <true/false/null>,
  "cancel_or_change": "<cancel, change, or null>",
  "edit_target": "<dish name they want to change, or null>",
  "edit_action": "<replace, remove, change_qty, change_preference, or null>",
  "edit_value": "<the new item name / quantity / preference text, or null>",
  "category": "<menu category they mentioned, as free text, or null>",
  "response_text": "<short warm natural reply, ONLY for genuine unrelated small talk, else empty string>"
}"""

EXPECTS_GUIDANCE = {
    "intent_and_table": "Figure out what they want (taking a food order is the main thing you handle) and pull out a table number if they mention one.",
    "table_no": "They should be telling you a table number. Extract it into table_no.",
    "items": "They're telling you what dish(es) they want. Extract every distinct dish mentioned into \"items\", each with its own quantity/preference.",
    "quantity": "They should be telling you how many. Extract quantity as an integer.",
    "preference": "They should be telling you a preference/customization, or declining one. If they decline (\"no\", \"nothing\", \"none\"), set yes_no=\"no\" and leave preference null.",
    "yes_no": "This is a yes/no question. Map informal replies (\"yeah\", \"nope\", \"sure\") onto yes_no. If they name a new dish instead of directly answering, still populate items[] and treat that as answering (answers_pending=true).",
    "yes_no_or_item": "This is an \"anything else?\" question. If they name a new dish, populate items[] — that counts as answering yes. Otherwise map their reply to yes_no/wants_more.",
    "cancel_or_change": "They just declined to confirm their order. Figure out if they want to cancel it outright or change something in it, and set cancel_or_change accordingly ('cancel' or 'change').",
    "edit": "They're telling you which order item to change and how (replace it / change quantity / change preference / remove it entirely). Fill edit_target/edit_action/edit_value.",
    "menu_category": "They're telling you which menu category they want to hear about. Extract it into category as free text — it doesn't need to exactly match a real category name, just capture what they said. If they instead named a specific dish, populate items[] instead of category.",
    "menu_next_step": "You just told them about a menu category. Figure out what they want next: order something (set intent=\"take_order\" and populate items[] if they named a dish), hear about a different category (extract it into category), or they're done for now (set yes_no=\"no\").",
}


def build_extraction_system_prompt(state: OrderState, expects: str) -> str:
    return f"""You are the understanding module for "Sonic", a restaurant robot taking a table's order by \
voice. Read the guest's latest utterance and return ONLY a JSON object (no prose, no markdown fences) with \
exactly this shape:

{EXTRACTION_SCHEMA}

Current stage: {expects} — {EXPECTS_GUIDANCE.get(expects, "")}
What was just asked: {state.pending_question or "nothing yet — this is the opening greeting"}
Order so far: {json.dumps(state.order_items, ensure_ascii=False) if state.order_items else "empty"}

Rules:
- answers_pending=false is a LAST RESORT — the guest is on a real mic/STT pipeline, so transcripts are often \
imperfect (dropped words, odd phrasing, mis-transcribed terms). Set answers_pending=true whenever there is ANY \
reasonable reading of the utterance as addressing what was just asked, even if it's incomplete, oddly \
phrased, or only partially matches — extract whatever you confidently can and leave the rest null rather than \
rejecting the whole utterance. Only set answers_pending=false when the utterance is genuinely about something \
else entirely, or is pure noise/unintelligible with no plausible connection to what was asked.
- Similarly, only leave yes_no null when the utterance truly gives no signal either way — when in doubt \
between a weak yes and null, prefer the yes/no reading over forcing a re-ask.
- Quantity: singular phrasing or "a"/"an" with no explicit number given -> quantity=1. Plural with no \
number given -> quantity=null (the caller will ask). An explicit number always wins.
- If multiple distinct dishes are named in one utterance (e.g. "two pizzas and a coke"), return one entry \
per dish in "items" — never merge them into a single name, never drop any.
- Treat informal affirmatives ("yeah", "yep", "sure", "go ahead") as yes_no="yes" and informal negatives \
("nah", "nope", "not really") as yes_no="no", without requiring the literal words.
- response_text is ONLY for genuine unrelated small talk (a brief, warm, natural reply) — leave it an \
empty string otherwise. Never wrap it in quotation marks.
- Numbers may be spoken as words ("two", "five") — always convert them to actual integers for quantity, \
and to a digit-only string for table_no. Never leave a number as a word in either field.
- intent must be exactly one of the values listed in the schema above, or null — never any other string, \
and never the current stage's name (e.g. don't set intent="yes_no" just because that's the current stage).
- Return valid JSON only, no other text. Every string value must be double-quoted.
"""


def _safe_int(v) -> Optional[int]:
    try:
        n = int(v)
        return n if n > 0 else None
    except (TypeError, ValueError):
        return None


def extract_slots(transcript: str, state: OrderState, expects: str) -> dict:
    system = build_extraction_system_prompt(state, expects)
    history_tail = state.conversation_history[-6:]
    history_text = "\n".join(f"{t['role']}: {t['text']}" for t in history_tail) or "(nothing yet)"
    user = f"Recent conversation:\n{history_text}\n\nLatest utterance: {transcript}"

    result = {}
    try:
        raw = llm.chat(system, user, json_mode=True, temperature=0.1)
        result = json.loads(raw)
    except GroqJSONError as e:
        print(f"[warn] extraction produced invalid JSON, asking it to correct itself: {e}")
        try:
            fix_messages = [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
                {"role": "assistant", "content": e.failed_generation or ""},
                {"role": "user", "content": "That was not valid JSON. Every string value must be double-quoted. "
                                             "Return the corrected JSON object only, no other text."},
            ]
            raw = llm.chat(system, user, json_mode=True, temperature=0.3, messages_override=fix_messages)
            result = json.loads(raw)
        except Exception as e2:
            print(f"[warn] extraction self-correction also failed: {e2}")
            result = {}
    except Exception as e:
        print(f"[warn] extraction call/parse failed: {e}")
        result = {}

    items = []
    for it in (result.get("items") or []):
        if isinstance(it, dict) and it.get("item_name"):
            items.append({
                "item_name": it.get("item_name"),
                "quantity": _safe_int(it.get("quantity")),
                "preference": it.get("preference") or None,
            })

    return {
        "intent": result.get("intent"),
        "table_no": result.get("table_no"),
        "answers_pending": bool(result.get("answers_pending", True)),
        "items": items,
        "quantity": _safe_int(result.get("quantity")),
        "preference": result.get("preference") or None,
        "yes_no": result.get("yes_no"),
        "wants_more": result.get("wants_more"),
        "cancel_or_change": result.get("cancel_or_change"),
        "edit_target": result.get("edit_target"),
        "edit_action": result.get("edit_action"),
        "edit_value": result.get("edit_value"),
        "category": result.get("category") or None,
        "response_text": clean_spoken_text(result.get("response_text")),
    }


def interpret(state: OrderState, transcript: str, expects: str) -> dict:
    state.conversation_history.append({"role": "user", "text": transcript})
    result = extract_slots(transcript, state, expects)
    trace("interpret", transcript=transcript, expects=expects, intent=result.get("intent"),
          answers_pending=result.get("answers_pending"), items=result.get("items"), yes_no=result.get("yes_no"))
    db_log_turn(state, "user", transcript, intent=result.get("intent"), slots=result)
    if result.get("table_no") and not state.table_no:
        state.table_no = str(result["table_no"])
    return result


# ---------------------------------------------------------------------------
# Shared ask/wait plumbing — every ask-node goes through this so timeout,
# off-topic redirect, and yes/no-ambiguity handling live in one place.
# ---------------------------------------------------------------------------

YES_NO_EXPECTS = {"yes_no", "yes_no_or_item"}
NEGATIVE_PREFERENCE_WORDS = {"none", "no", "no preference", "nothing", "nope", "not really"}


def get_reply_or_route(state: OrderState, this_node: str, purpose: str, expects: str, **ctx):
    """Returns the extraction outcome dict if the node should keep
    processing it, or None if state.next_node was already set (caller should
    just `return asdict(state)` immediately)."""
    if state.pending_seed is not None:
        outcome = state.pending_seed
        state.pending_seed = None
    else:
        prompt = render(purpose, state, **ctx)
        answer = interrupt({"prompt": prompt})
        if answer == TIMEOUT_SENTINEL:
            say("idle_timeout_farewell", state)
            state.went_idle = True
            state.next_node = "n_respond"
            return None
        state.pending_question = purpose
        outcome = interpret(state, answer, expects)

    if not outcome.get("answers_pending", True):
        last_said = state.conversation_history[-1]["text"] if state.conversation_history else ""
        aside = outcome.get("response_text") or render("redirect_off_topic", state, last_said=last_said)
        speak_text(aside)
        state.next_node = this_node
        return None

    if expects in YES_NO_EXPECTS and outcome.get("yes_no") not in ("yes", "no") and not outcome.get("items"):
        say("yes_no_unclear", state)
        state.next_node = this_node
        return None

    return outcome


# ---------------------------------------------------------------------------
# Graph nodes
# ---------------------------------------------------------------------------

def commit_and_continue(state: OrderState) -> str:
    state.order_items.append(state.active_item)
    state.active_item = None
    return "n_extract_items" if state.pending_items else "n_ask_anything_else"


def route_active_item(state: OrderState) -> str:
    item = state.active_item
    if item["quantity"] is None:
        return "n_ask_qty"
    if not item["preference_asked"]:
        return "n_ask_preference"
    return commit_and_continue(state)


def n_intent_classify(state: OrderState) -> dict:
    trace_node("n_intent_classify", state)

    if state.first_turn and FORCED_LOCATION and FORCED_ACTION:
        state.first_turn = False
        state.trigger_source = "ui"
        state.table_no = FORCED_LOCATION
        if FORCED_ACTION in DISPATCH_TAKE_ORDER_ACTIONS:
            state.post_arrival_node = "n_greet_and_ask_order"
            state.next_node = "n_navigate_to_table"
        elif FORCED_ACTION == "deliver":
            state.post_arrival_node = "n_deliver_announce"
            state.next_node = "n_navigate_to_table"
        else:
            state.next_node = "n_stub"
            state.pending_seed = {"stub_intent": FORCED_ACTION}
        return asdict(state)

    state.trigger_source = "voice"
    if state.pending_seed is not None:
        outcome = state.pending_seed
        state.pending_seed = None
    else:
        prompt = render("ask_how_can_i_help", state)
        answer = interrupt({"prompt": prompt})
        if answer == TIMEOUT_SENTINEL:
            say("idle_timeout_farewell", state)
            state.went_idle = True
            state.next_node = "n_respond"
            return asdict(state)
        state.first_turn = False
        state.pending_question = "top-level: how can I help"
        outcome = interpret(state, answer, expects="intent_and_table")

    intent = outcome.get("intent") or "normal_conv"
    if intent == "take_order":
        state.post_arrival_node = "n_greet_and_ask_order"
        state.pending_seed = outcome if outcome.get("items") else None
        state.next_node = "n_navigate_to_table" if state.table_no else "n_ask_table"
    elif intent == "menu":
        state.post_arrival_node = "n_menu_pick_category"
        state.pending_seed = outcome if (outcome.get("items") or outcome.get("category")) else None
        state.next_node = "n_navigate_to_table" if state.table_no else "n_ask_table"
    else:
        state.pending_seed = {"stub_intent": intent}
        state.next_node = "n_stub"
    return asdict(state)


def n_ask_table(state: OrderState) -> dict:
    trace_node("n_ask_table", state)
    purpose = "ask_table_retry" if state.ask_retry else "ask_table"
    outcome = get_reply_or_route(state, "n_ask_table", purpose, expects="table_no")
    if outcome is None:
        return asdict(state)
    if not state.table_no:
        # loop back into THIS SAME ask (retry-flavored) instead of speaking
        # a retry line and then separately re-asking the original question —
        # one spoken line, one listen, every time
        state.ask_retry = True
        state.next_node = "n_ask_table"
        return asdict(state)
    state.ask_retry = False
    state.next_node = "n_navigate_to_table"
    return asdict(state)


def n_navigate_to_table(state: OrderState) -> dict:
    trace_node("n_navigate_to_table", state)
    if state.location_reached:
        state.next_node = state.post_arrival_node
        return asdict(state)
    # table_ref is what actually gets searched for in the waypoints file —
    # the real waypoint name (see table_ref_for_nav), not a guessed/rebuilt
    # string — used identically for the nav_bridge call, the phase report,
    # and the spoken line so all three always agree with each other.
    table_ref = table_ref_for_nav(state.table_no)
    report_phase("heading_to_table", f"Heading to {table_ref}", state.table_no)
    arrived = perform_travel_action(state, "heading_to_table", table_ref, table_ref=table_ref)
    if not arrived:
        say("apology_nav_failed", state)
        state.went_idle = True
        state.next_node = "n_respond"
        return asdict(state)
    state.location_reached = True
    report_phase("arrived", f"Arrived at {table_ref}", state.table_no)
    db_start_session(state)
    state.next_node = state.post_arrival_node
    return asdict(state)


def n_deliver_announce(state: OrderState) -> dict:
    """Dispatched via the table card's "Deliver" button (SONIC_ACTION_HINT=
    deliver) — the food's already on the robot, staged by kitchen staff
    before dispatch; this just announces arrival and waits for the guest to
    physically take it before heading back. ask_retry reused here exactly
    like n_ask_table/n_ask_qty use it — same node, retry-flavored purpose
    on the loop-back rather than repeating the identical "it's here" line."""
    trace_node("n_deliver_announce", state)
    purpose = "delivery_confirm_retry" if state.ask_retry else "delivery_arrived"
    outcome = get_reply_or_route(state, "n_deliver_announce", purpose, expects="yes_no")
    if outcome is None:
        return asdict(state)
    if outcome.get("yes_no") == "yes":
        state.ask_retry = False
        say("delivery_confirmed", state)
        state.went_idle = True
        state.next_node = "n_respond"
        return asdict(state)
    state.ask_retry = True
    state.next_node = "n_deliver_announce"
    return asdict(state)


def n_greet_and_ask_order(state: OrderState) -> dict:
    trace_node("n_greet_and_ask_order", state)
    report_phase("taking_order", "Taking order", state.table_no)
    if state.pending_seed is not None and state.pending_seed.get("items"):
        state.next_node = "n_extract_items"
        return asdict(state)

    prompt = render("arrived_greet_and_ask_order", state)
    answer = interrupt({"prompt": prompt})
    if answer == TIMEOUT_SENTINEL:
        say("idle_timeout_farewell", state)
        state.went_idle = True
        state.next_node = "n_respond"
        return asdict(state)
    state.pending_question = "arrived_greet_and_ask_order"
    outcome = interpret(state, answer, expects="items")
    state.pending_seed = outcome
    state.next_node = "n_extract_items"
    return asdict(state)


def _menu_handoff_to_order(state: OrderState, outcome: dict) -> None:
    """The guest said something like "I'd like to order" while browsing the
    menu — seed n_extract_items exactly the way n_greet_and_ask_order does
    (a pending_seed with an "items" list, or None to fall through to a fresh
    "what would you like" ask if no dish was named yet). table_no/
    location_reached are already set since this only ever runs after
    n_navigate_to_table succeeded."""
    items = outcome.get("items") or []
    state.pending_seed = {"items": items} if items else None
    state.active_menu_category = None
    state.category_intro_said = False
    state.next_node = "n_extract_items"


def _order_handoff_to_menu(state: OrderState, outcome: dict) -> None:
    """Symmetric to _menu_handoff_to_order() — the guest asked about the
    menu ("what do you have", "what's on the menu") while already in the
    order flow instead of naming a dish. Without this, n_extract_items has
    no way to tell that apart from a mis-heard/unmatched dish name, and
    just apologizes and re-asks for a dish forever. Seeds
    n_menu_pick_category the same seeded-fast-path way, so a category they
    already mentioned carries straight through instead of a fresh re-ask."""
    state.pending_seed = outcome if (outcome.get("items") or outcome.get("category")) else None
    state.active_menu_category = None
    state.category_intro_said = False
    state.next_node = "n_menu_pick_category"


def n_menu_pick_category(state: OrderState) -> dict:
    trace_node("n_menu_pick_category", state)
    purpose = "menu_ask_category_retry" if state.ask_retry else "menu_ask_category"
    outcome = get_reply_or_route(state, "n_menu_pick_category", purpose,
                                  expects="menu_category", categories=", ".join(menu_categories()))
    if outcome is None:
        return asdict(state)

    if outcome.get("intent") == "take_order":
        _menu_handoff_to_order(state, outcome)
        return asdict(state)

    if outcome.get("items"):
        item = find_menu_item(outcome["items"][0]["item_name"])
        if item:
            state.active_menu_category = item["category"]
            state.ask_retry = False
            state.category_intro_said = False
            state.next_node = "n_menu_answer_questions"
            return asdict(state)
        # named dish didn't match anything on the menu — fall through to
        # try matching a category instead, same as if none had been named

    matched = find_menu_category(outcome.get("category"))
    if not matched:
        state.ask_retry = True
        state.next_node = "n_menu_pick_category"
        return asdict(state)

    state.ask_retry = False
    state.active_menu_category = matched
    state.category_intro_said = False
    state.next_node = "n_menu_answer_questions"
    return asdict(state)


def n_menu_answer_questions(state: OrderState) -> dict:
    trace_node("n_menu_answer_questions", state)
    items = menu_items_summary(menu_items_by_category(state.active_menu_category))

    if state.category_intro_said:
        purpose = "menu_answer_question"
        question = state.conversation_history[-1]["text"] if state.conversation_history else ""
        ctx = dict(category=state.active_menu_category, items=items, question=question)
    else:
        purpose = "menu_describe_category"
        ctx = dict(category=state.active_menu_category, items=items)

    outcome = get_reply_or_route(state, "n_menu_answer_questions", purpose,
                                  expects="menu_next_step", **ctx)
    if outcome is None:
        return asdict(state)
    state.category_intro_said = True

    if outcome.get("intent") == "take_order":
        _menu_handoff_to_order(state, outcome)
        return asdict(state)

    if outcome.get("category"):
        matched = find_menu_category(outcome["category"])
        if matched and matched != state.active_menu_category:
            state.active_menu_category = matched
            state.category_intro_said = False
            state.next_node = "n_menu_answer_questions"
            return asdict(state)

    if outcome.get("yes_no") == "no":
        say("menu_browse_farewell", state)
        state.went_idle = True
        state.next_node = "n_respond"
        return asdict(state)

    # A genuine follow-up question, not a clean category-switch or a "no" —
    # loop back; next pass answers it (menu_answer_question's {question}
    # context) via the branch above, then re-listens for what's next.
    state.next_node = "n_menu_answer_questions"
    return asdict(state)


def n_extract_items(state: OrderState) -> dict:
    trace_node("n_extract_items", state)
    if state.pending_seed is not None:
        outcome = state.pending_seed
        state.pending_seed = None
    elif state.pending_items:
        outcome = {"items": [state.pending_items.pop(0)], "answers_pending": True}
    else:
        # A prior menu-match failure asks WITH the "sorry, couldn't find X,
        # say it again" purpose directly, instead of speaking that as a
        # standalone aside and then separately re-asking a generic
        # "what would you like" question before ever listening.
        if state.item_attempts > 0:
            outcome = get_reply_or_route(state, "n_extract_items", "item_not_found", expects="items",
                                          item_name=state.last_unmatched_item or "that")
        else:
            outcome = get_reply_or_route(state, "n_extract_items", "ask_what_would_you_like", expects="items")
        if outcome is None:
            return asdict(state)

    if outcome.get("intent") == "menu" and not outcome.get("items"):
        _order_handoff_to_menu(state, outcome)
        return asdict(state)

    items = outcome.get("items") or []
    if not items:
        state.item_attempts += 1
        if state.item_attempts >= 3:
            say("reprompt_unclear_item", state)
            state.went_idle = True
            state.next_node = "n_respond"
            return asdict(state)
        state.last_unmatched_item = "that"
        state.next_node = "n_extract_items"
        return asdict(state)

    first, rest = items[0], items[1:]
    match = find_menu_item(first.get("item_name"))
    if not match:
        state.item_attempts += 1
        if state.item_attempts >= 3:
            say("reprompt_unclear_item", state)
            state.went_idle = True
            state.next_node = "n_respond"
            return asdict(state)
        state.last_unmatched_item = first.get("item_name") or "that"
        state.next_node = "n_extract_items"
        return asdict(state)
    state.item_attempts = 0
    state.last_unmatched_item = None

    if rest:
        state.pending_items.extend(rest)

    state.active_item = {
        "item_id": match["item_id"], "name": match["name"], "category": match["category"],
        "quantity": first.get("quantity"), "preference": first.get("preference"),
        "preference_asked": bool(first.get("preference")),
    }
    state.next_node = route_active_item(state)
    return asdict(state)


def n_ask_qty(state: OrderState) -> dict:
    trace_node("n_ask_qty", state)
    purpose = "ask_quantity_retry" if state.ask_retry else "ask_quantity"
    outcome = get_reply_or_route(state, "n_ask_qty", purpose, expects="quantity",
                                  item_name=state.active_item["name"])
    if outcome is None:
        return asdict(state)
    qty = outcome.get("quantity")
    if not qty:
        state.ask_retry = True
        state.next_node = "n_ask_qty"
        return asdict(state)
    state.ask_retry = False
    state.active_item["quantity"] = qty
    state.next_node = "n_ask_preference" if not state.active_item["preference_asked"] else commit_and_continue(state)
    return asdict(state)


def n_ask_preference(state: OrderState) -> dict:
    trace_node("n_ask_preference", state)
    outcome = get_reply_or_route(state, "n_ask_preference", "ask_preference", expects="preference",
                                  item_name=state.active_item["name"])
    if outcome is None:
        return asdict(state)
    pref = outcome.get("preference")
    if outcome.get("yes_no") == "no" or (pref and str(pref).strip().lower() in NEGATIVE_PREFERENCE_WORDS):
        pref = None
    state.active_item["preference"] = pref
    state.active_item["preference_asked"] = True
    state.next_node = commit_and_continue(state)
    return asdict(state)


def n_ask_anything_else(state: OrderState) -> dict:
    trace_node("n_ask_anything_else", state)
    outcome = get_reply_or_route(state, "n_ask_anything_else", "ask_anything_else", expects="yes_no_or_item")
    if outcome is None:
        return asdict(state)
    if outcome.get("items"):
        state.pending_seed = outcome
        state.next_node = "n_extract_items"
        return asdict(state)
    if outcome.get("yes_no") == "yes" or outcome.get("wants_more") is True:
        state.next_node = "n_extract_items"
        return asdict(state)
    state.next_node = "n_confirm_order"
    return asdict(state)


def n_confirm_order(state: OrderState) -> dict:
    trace_node("n_confirm_order", state)
    outcome = get_reply_or_route(state, "n_confirm_order", "confirm_readback", expects="yes_no",
                                  order_summary=order_summary(state))
    if outcome is None:
        return asdict(state)
    state.next_node = "n_finalize_order" if outcome.get("yes_no") == "yes" else "n_confirm_reject"
    return asdict(state)


def n_confirm_reject(state: OrderState) -> dict:
    trace_node("n_confirm_reject", state)
    outcome = get_reply_or_route(state, "n_confirm_reject", "confirm_reject_choice", expects="cancel_or_change")
    if outcome is None:
        return asdict(state)
    choice = outcome.get("cancel_or_change") or outcome.get("yes_no")
    if choice in ("cancel", "no"):
        state.next_node = "n_cancel_order"
    elif choice in ("change", "yes"):
        state.next_node = "n_edit_order_start"
    else:
        say("cancel_or_change_unclear", state)
        state.next_node = "n_confirm_reject"
    return asdict(state)


def n_cancel_order(state: OrderState) -> dict:
    trace_node("n_cancel_order", state)
    state.order_items = []
    say("cancel_confirmed", state)
    state.went_idle = True
    state.next_node = "n_respond"
    return asdict(state)


def n_edit_order_start(state: OrderState) -> dict:
    trace_node("n_edit_order_start", state)
    if not state.order_items:
        say("nothing_to_edit", state)
        state.went_idle = True
        state.next_node = "n_respond"
        return asdict(state)
    outcome = get_reply_or_route(state, "n_edit_order_start", "edit_ask_target", expects="edit",
                                  order_summary=order_summary(state))
    if outcome is None:
        return asdict(state)
    target = find_order_line(state, outcome.get("edit_target"))
    if not target:
        say("edit_target_not_found", state, item_name=outcome.get("edit_target") or "that item")
        state.next_node = "n_edit_order_start"
        return asdict(state)
    state.edit_target_name = target["name"]
    state.pending_seed = outcome
    state.next_node = "n_edit_apply"
    return asdict(state)


def n_edit_apply(state: OrderState) -> dict:
    trace_node("n_edit_apply", state)
    outcome = state.pending_seed or {}
    state.pending_seed = None
    target = find_order_line(state, state.edit_target_name)
    if not target:
        state.next_node = "n_confirm_order"
        return asdict(state)

    action = outcome.get("edit_action") or "replace"
    value = outcome.get("edit_value")
    if action == "remove":
        state.order_items.remove(target)
        summary = f"removed {target['name']}"
    elif action == "change_qty":
        qty = _safe_int(value)
        if qty:
            target["quantity"] = qty
            summary = f"{target['name']} quantity updated to {qty}"
        else:
            summary = f"kept {target['name']} as is"
    elif action == "change_preference":
        target["preference"] = value
        summary = f"updated {target['name']}'s preference"
    else:
        match = find_menu_item(value)
        if match:
            target.update(item_id=match["item_id"], name=match["name"], category=match["category"])
            summary = f"replaced with {match['name']}"
        else:
            summary = f"couldn't find \"{value or 'that'}\" on the menu, kept {target['name']}"

    say("edit_applied", state, change_summary=summary)
    state.next_node = "n_confirm_order"
    return asdict(state)


def n_finalize_order(state: OrderState) -> dict:
    trace_node("n_finalize_order", state)
    if not state.order_items:
        say("nothing_new_to_confirm", state)
        state.went_idle = True
        state.next_node = "n_respond"
        return asdict(state)
    total = sum(get_item_price(i) * i["quantity"] for i in state.order_items)
    state.order_total = total
    db_place_order(state, state.order_items, total)
    say("closing_thanks", state, order_summary=order_summary(state))
    state.went_idle = True
    state.next_node = "n_respond"
    return asdict(state)


def n_stub(state: OrderState) -> dict:
    trace_node("n_stub", state)
    requested = "that"
    if state.pending_seed:
        requested = state.pending_seed.get("stub_intent") or state.pending_seed.get("intent") or "that"
        state.pending_seed = None
    say("stub_unavailable", state, requested_intent=requested)
    state.went_idle = True
    state.next_node = "n_respond"
    return asdict(state)


def n_respond(state: OrderState) -> dict:
    trace_node("n_respond", state)
    state.pending_question = None
    state.item_attempts = 0
    state.pending_seed = None
    state.ask_retry = False
    state.last_unmatched_item = None
    db_end_session(state)
    state.next_node = "n_return_to_kitchen"
    return asdict(state)


def n_return_to_kitchen(state: OrderState) -> dict:
    trace_node("n_return_to_kitchen", state)
    if state.location_reached:
        report_phase("heading_to_kitchen", "Heading back to kitchen", state.table_no)
        navigate_and_wait("Kitchen")
    state.table_no = None
    state.location_reached = False
    state.next_node = "END"
    return asdict(state)


# ---------------------------------------------------------------------------
# Graph assembly
# ---------------------------------------------------------------------------

NODE_FUNCS = {
    "n_intent_classify": n_intent_classify,
    "n_ask_table": n_ask_table,
    "n_navigate_to_table": n_navigate_to_table,
    "n_deliver_announce": n_deliver_announce,
    "n_greet_and_ask_order": n_greet_and_ask_order,
    "n_menu_pick_category": n_menu_pick_category,
    "n_menu_answer_questions": n_menu_answer_questions,
    "n_extract_items": n_extract_items,
    "n_ask_qty": n_ask_qty,
    "n_ask_preference": n_ask_preference,
    "n_ask_anything_else": n_ask_anything_else,
    "n_confirm_order": n_confirm_order,
    "n_confirm_reject": n_confirm_reject,
    "n_cancel_order": n_cancel_order,
    "n_edit_order_start": n_edit_order_start,
    "n_edit_apply": n_edit_apply,
    "n_finalize_order": n_finalize_order,
    "n_stub": n_stub,
    "n_respond": n_respond,
    "n_return_to_kitchen": n_return_to_kitchen,
}


def _route_by_next_node(state: OrderState) -> str:
    return state.next_node


def build_graph():
    g = StateGraph(OrderState)
    for name, fn in NODE_FUNCS.items():
        g.add_node(name, fn)
    g.set_entry_point("n_intent_classify")

    edge_map = {name: name for name in NODE_FUNCS}
    edge_map["END"] = END
    for name in NODE_FUNCS:
        g.add_conditional_edges(name, _route_by_next_node, edge_map)

    return g.compile(checkpointer=MemorySaver())


# ---------------------------------------------------------------------------
# Outer driver
# ---------------------------------------------------------------------------

def run_graph_session(app) -> None:
    """Drives one compiled LangGraph run start-to-finish, handling the
    interrupt/resume protocol with real (or text-mode) speak/listen I/O.
    Each call is a fully self-contained visit (no cross-session order
    carry-over — every terminal path clears table_no/order_items before
    returning to the wake-word loop)."""
    global _current_state

    state = OrderState()
    if FORCED_LOCATION:
        state.table_no = FORCED_LOCATION
        state.trigger_source = "ui"
    _current_state = state

    thread_id = f"main-agent-{uuid_module.uuid4().hex[:8]}"
    config = {"configurable": {"thread_id": thread_id}}
    try:
        result = app.invoke(asdict(state), config)
        while True:
            interrupts = result.get("__interrupt__")
            if not interrupts:
                return
            payload = interrupts[0].value
            prompt_text = payload["prompt"] if isinstance(payload, dict) else str(payload)
            transcript = listen_with_patience(prompt_text)
            resume_value = transcript if transcript is not None else TIMEOUT_SENTINEL
            result = app.invoke(Command(resume=resume_value), config)
    finally:
        # Whether the session ended normally, on an exception, or mid-visit,
        # the dashboard must never keep showing a stale in-progress phase.
        report_phase(None)


# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------

def main_loop() -> None:
    app = build_graph()

    if TEXT_MODE:
        print("=== main_agent.py (text mode) — no mic, no wake word, no Sarvam calls ===")
        print("Type your first utterance directly (the greeting is simulated).")
        print("Press Enter on a blank line to simulate silence/timeout. Type 'quit' to exit.\n")
        while True:
            run_graph_session(app)
    elif FORCED_LOCATION:
        require_api_keys()
        action_label = FORCED_ACTION or "order"
        print(f"main_agent dispatched: table={FORCED_LOCATION} action={action_label!r} (no wake word needed).")
        navigate_and_wait("Kitchen")
        run_graph_session(app)
    else:
        require_api_keys()
        oww_model = load_wake_word_model()
        print(f"main_agent is listening for the wake word ('{WAKE_WORD_NAME}')...")
        while True:
            wait_for_wake_word(oww_model)
            run_graph_session(app)


def main() -> None:
    global TEXT_MODE, SONIC_SKIP_NAV
    parser = argparse.ArgumentParser(description="Sonic main_agent — unified take-order voice agent")
    parser.add_argument("--text-mode", action="store_true",
                        help="Run with typed input/printed output instead of mic/speaker/wake-word")
    parser.add_argument("--test-mode", action="store_true",
                        help="Skip real Nav2 trips (instant-arrival) — everything else (wake word, "
                             "mic, STT, LLM, TTS) stays real, so the NLP flow can be exercised end to "
                             "end without a working ROS/Nav2 setup. Same effect as SONIC_SKIP_NAV=1.")
    args = parser.parse_args()
    TEXT_MODE = args.text_mode
    SONIC_SKIP_NAV = SONIC_SKIP_NAV or args.test_mode

    if TEXT_MODE:
        require_api_keys(need_sarvam=False)
    if SONIC_SKIP_NAV:
        print("[main] test mode — navigation will be skipped (instant arrival), everything else is real")
    print("Runtime: LangGraph StateGraph, humanized (every spoken line is an LLM call — see render()).")
    print(f"Node-execution tracing: {'ON' if TRACE_ENABLED else 'OFF'} (set SONIC_TRACE=0 to disable)")
    resolve_robot()
    load_menu_from_db()
    if FORCED_LOCATION:
        print(f"[db] TABLE_NO={FORCED_LOCATION!r} set — session will skip conversational table discovery")
    main_loop()


if __name__ == "__main__":
    main()
